apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podcasticot
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: podcasticot.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podcasticot
                port:
                  number: 80
